/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Maarloon
 */
public class PESQUISA extends javax.swing.JInternalFrame {

    /**
     * Creates new form PESQUISA
     */
    public PESQUISA() {
        initComponents();
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LCODIGO = new javax.swing.JLabel();
        LNOME = new javax.swing.JLabel();
        LNASCIMENTO = new javax.swing.JLabel();
        LCPF = new javax.swing.JLabel();
        LSANGUE = new javax.swing.JLabel();
        LCONTATO = new javax.swing.JLabel();
        LSUS = new javax.swing.JLabel();
        LOBSERVACOES = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBorder(null);
        setMaximumSize(new java.awt.Dimension(590, 638));
        setMinimumSize(new java.awt.Dimension(590, 638));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        LCODIGO.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LCODIGO.setText("#3695814723");
        jPanel1.add(LCODIGO);
        LCODIGO.setBounds(90, 20, 420, 30);

        LNOME.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LNOME.setText("Soraya dos Santos");
        jPanel1.add(LNOME);
        LNOME.setBounds(90, 90, 420, 30);

        LNASCIMENTO.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LNASCIMENTO.setText("12/09/1957");
        jPanel1.add(LNASCIMENTO);
        LNASCIMENTO.setBounds(90, 160, 100, 30);

        LCPF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LCPF.setText("    119.359.698-89");
        jPanel1.add(LCPF);
        LCPF.setBounds(220, 160, 180, 30);

        LSANGUE.setText("SANGUE");
        jPanel1.add(LSANGUE);
        LSANGUE.setBounds(420, 160, 80, 30);

        LCONTATO.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LCONTATO.setText("    (58) 99188-3065");
        jPanel1.add(LCONTATO);
        LCONTATO.setBounds(320, 230, 180, 30);

        LSUS.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LSUS.setText(" 256987456231456");
        jPanel1.add(LSUS);
        LSUS.setBounds(90, 230, 160, 30);

        LOBSERVACOES.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LOBSERVACOES.setText("Soraya é alérgica a amendoim e lactose. ");
        jPanel1.add(LOBSERVACOES);
        LOBSERVACOES.setBounds(90, 290, 420, 50);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("NÃO reanimar caso sofra parada cardíada. ");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(90, 550, 350, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Avisar seu filho Rubens (contato de emergência).");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(90, 500, 400, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("PROBLEMAS RESPIRATÓRIOS; ");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(90, 450, 260, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("DIABETES MELLITUS; ");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(90, 400, 190, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Possui doenças crônicas, como:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(90, 340, 400, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGENS/TELA DE PESQUISA (CERTO).png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, -10, 590, 634);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 590, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LCODIGO;
    private javax.swing.JLabel LCONTATO;
    private javax.swing.JLabel LCPF;
    private javax.swing.JLabel LNASCIMENTO;
    private javax.swing.JLabel LNOME;
    private javax.swing.JLabel LOBSERVACOES;
    private javax.swing.JLabel LSANGUE;
    private javax.swing.JLabel LSUS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
