
import javax.swing.plaf.basic.BasicInternalFrameUI;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Maarloon
 */
public class TELA_PADRAO extends javax.swing.JFrame {

    /**
     * Creates new form TELA_PADRAO
     */
    public TELA_PADRAO() {
        initComponents();
       AJUDA help = new AJUDA();
       DESK_ADD.add(help);
       help.setVisible(true);
       BasicInternalFrameUI XI = (BasicInternalFrameUI)help.getUI();
       XI.setNorthPane(null);
       help.setSize(590,634);
        
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblsus = new javax.swing.JLabel();
        BPESQUISA = new javax.swing.JButton();
        BAJUDA = new javax.swing.JButton();
        BEDITAR = new javax.swing.JButton();
        BCADASTRO = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        DESK_ADD = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 598));
        setMinimumSize(new java.awt.Dimension(800, 598));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(800, 598));
        getContentPane().setLayout(null);

        lblsus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGENS/Design sem nome (42)2222.png"))); // NOI18N
        getContentPane().add(lblsus);
        lblsus.setBounds(610, 60, 170, 170);

        BPESQUISA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGENS/Design sem nome (42).png"))); // NOI18N
        BPESQUISA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BPESQUISAActionPerformed(evt);
            }
        });
        getContentPane().add(BPESQUISA);
        BPESQUISA.setBounds(620, 340, 150, 40);

        BAJUDA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGENS/Design sem nome (45).png"))); // NOI18N
        BAJUDA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAJUDAActionPerformed(evt);
            }
        });
        getContentPane().add(BAJUDA);
        BAJUDA.setBounds(620, 520, 150, 40);

        BEDITAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGENS/Design sem nome (44).png"))); // NOI18N
        getContentPane().add(BEDITAR);
        BEDITAR.setBounds(620, 460, 150, 40);

        BCADASTRO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGENS/Design sem nome (43).png"))); // NOI18N
        BCADASTRO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BCADASTROMouseClicked(evt);
            }
        });
        BCADASTRO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCADASTROActionPerformed(evt);
            }
        });
        getContentPane().add(BCADASTRO);
        BCADASTRO.setBounds(620, 400, 150, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGENS/FECHAR4.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3);
        jLabel3.setBounds(750, 10, 40, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGENS/Design sem nome (41).png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(590, 0, 210, 600);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout DESK_ADDLayout = new javax.swing.GroupLayout(DESK_ADD);
        DESK_ADD.setLayout(DESK_ADDLayout);
        DESK_ADDLayout.setHorizontalGroup(
            DESK_ADDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );
        DESK_ADDLayout.setVerticalGroup(
            DESK_ADDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DESK_ADD)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DESK_ADD)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 590, 600);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BCADASTROMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BCADASTROMouseClicked

        
        
    }//GEN-LAST:event_BCADASTROMouseClicked

    private void BCADASTROActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCADASTROActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BCADASTROActionPerformed

    private void BAJUDAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAJUDAActionPerformed
        AJUDA TA = new AJUDA();
        DESK_ADD.add(TA);
        TA.setVisible(true);
        TA.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI BI = (BasicInternalFrameUI)TA.getUI();
        BI.setNorthPane(null);
        TA.setSize(590,634);        TA.setSize(590,634);    }//GEN-LAST:event_BAJUDAActionPerformed

    private void BPESQUISAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BPESQUISAActionPerformed
        TELA_INICIAL TI = new TELA_INICIAL();
        DESK_ADD.add(TI);
        TI.setVisible(true);
        BasicInternalFrameUI XI = (BasicInternalFrameUI)TI.getUI();
        XI.setNorthPane(null);
        TI.setSize(590,634);
        
    }//GEN-LAST:event_BPESQUISAActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TELA_PADRAO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TELA_PADRAO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TELA_PADRAO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TELA_PADRAO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TELA_PADRAO().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BAJUDA;
    private javax.swing.JButton BCADASTRO;
    private javax.swing.JButton BEDITAR;
    private javax.swing.JButton BPESQUISA;
    private javax.swing.JDesktopPane DESK_ADD;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblsus;
    // End of variables declaration//GEN-END:variables
}
