
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Maarloon
 */
public class TELA_INICIAL extends javax.swing.JInternalFrame {

    /**
     * Creates new form CADASTRO
     */
    ImageIcon lupa = new ImageIcon("C:/Users/Maarloon/Desktop/Search.gif");
    ImageIcon inicio1 = new ImageIcon("C:/Users/Maarloon/Downloads/TELA INICIAL.png");
    ImageIcon aguarde = new ImageIcon("C:/Users/Maarloon/Downloads/TELA INICIAL (1).png");
    int etapa= 1;
    public TELA_INICIAL() {
        initComponents();
        lbllupa.setVisible(false);
        lupa.setImage(lupa.getImage().getScaledInstance(lbllupa.getWidth(),lbllupa.getHeight(), 1));
        lbllupa.setIcon(lupa);
        lblcapa.setIcon(inicio1);
        inicio();
    }
public void timer(){
        try {
            this.wait(1000);
        } catch (InterruptedException ex) {
            Logger.getLogger(TELA_INICIAL.class.getName()).log(Level.SEVERE, null, ex);
        }
}

public void inicio(){
    timer();
    inicio2();
}
public void inicio2(){
    lbllupa.setVisible(true);
    lblcapa.setIcon(aguarde);
    timer();
    concluido();
}
public void concluido(){
    timer();
    PESQUISA tp = new PESQUISA();
    
    tp.setVisible(true);
    BasicInternalFrameUI XI = (BasicInternalFrameUI)tp.getUI();
    XI.setNorthPane(null);
    tp.setSize(590,634);     
    this.dispose();
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbllupa = new javax.swing.JLabel();
        lblcapa = new javax.swing.JLabel();

        setBorder(null);
        getContentPane().setLayout(null);
        getContentPane().add(lbllupa);
        lbllupa.setBounds(160, 260, 270, 230);

        lblcapa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGENS/TELA INICIAL.png"))); // NOI18N
        getContentPane().add(lblcapa);
        lblcapa.setBounds(0, 0, 600, 634);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblcapa;
    private javax.swing.JLabel lbllupa;
    // End of variables declaration//GEN-END:variables
}
